# Generated by Django 4.2.17 on 2025-07-07 23:16

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Alliance Auth
import allianceauth.framework.api.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LawnSkyhooks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("basic_access", "Can access this app"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Skyhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Name or system of the Skyhook's location.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("magmatic gas", "Magmatic Gas"),
                            ("superionic ice", "Superionic Ice"),
                        ],
                        help_text="Type of resource this Skyhook accumulates.",
                        max_length=50,
                    ),
                ),
                (
                    "resource_per_minute",
                    models.FloatField(
                        default=0.0,
                        help_text="Accumulation rate of the resource per minute.",
                    ),
                ),
                (
                    "last_emptied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this Skyhook was last emptied.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmptyLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emptied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skyhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lawn_skyhooks.skyhook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(
                            allianceauth.framework.api.user.get_sentinel_user
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
