# Generated by Django 4.2.18 on 2025-10-19 15:37

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawn_skyhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emptylog",
            name="amount_taken",
            field=models.FloatField(
                default=0.0, help_text="Amount removed from the Skyhook"
            ),
        ),
    ]
