# Generated by Django 4.2.18 on 2025-10-19 15:57

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lawn_skyhooks", "0002_emptylog_amount_taken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lawnskyhooks",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("view_skyhook_logs", "Can view skyhook logs"),
                ),
            },
        ),
    ]
