# Generated by Django 4.2.27 on 2026-02-15 23:57

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawn_skyhooks", "0003_alter_lawnskyhooks_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="skyhook",
            name="next_vulnerable_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skyhook",
            name="last_emptied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skyhook",
            name="location",
            field=models.CharField(
                help_text="Name of the Skyhook location e.g. 'BZ-BCK III'.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="skyhook",
            name="resource_per_minute",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="skyhook",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("magmatic gas", "Magmatic Gas"),
                    ("superionic ice", "Superionic Ice"),
                ],
                max_length=50,
            ),
        ),
    ]
