# Generated by Django 4.2.27 on 2026-02-16 02:36

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lawn_skyhooks", "0004_skyhook_next_vulnerable_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skyhook",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the skyhook was claimed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="skyhook",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently working on emptying this skyhook.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_skyhooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
