# Generated by Django 4.2.27 on 2026-02-16 02:54

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lawn_skyhooks", "0005_skyhook_claimed_at_skyhook_claimed_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lawnskyhooks",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("view_skyhook_logs", "Can view skyhook logs"),
                    ("import_skyhooks", "Can import skyhook data"),
                ),
            },
        ),
    ]
