# Generated by Django 4.2.27 on 2026-02-16 03:11

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawn_skyhooks", "0006_alter_lawnskyhooks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnerableLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_vulnerable_at", models.DateTimeField()),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skyhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerable_logs",
                        to="lawn_skyhooks.skyhook",
                    ),
                ),
            ],
        ),
    ]
